using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Handwriting_Generator
{
    public enum FChar
    {
        rus_1,
        rus_2,
        rus_3,
        rus_4,
        rus_5,
        rus_6,
        rus_7,
        rus_8,
        rus_9,
        rus_10,
        rus_11,
        rus_12,
        rus_13,
        rus_14,
        rus_15,
        rus_16,
        rus_17,
        rus_18,
        rus_19,
        rus_20,
        rus_21,
        rus_22,
        rus_23,
        rus_24,
        rus_25,
        rus_26,
        rus_27,
        rus_28,
        rus_29,
        rus_30,
        rus_31,
        rus_32,
        rus_33,

        rus_1_cap,
        rus_2_cap,
        rus_3_cap,
        rus_4_cap,
        rus_5_cap,
        rus_6_cap,
        rus_7_cap,
        rus_8_cap,
        rus_9_cap,
        rus_10_cap,
        rus_11_cap,
        rus_12_cap,
        rus_13_cap,
        rus_14_cap,
        rus_15_cap,
        rus_16_cap,
        rus_17_cap,
        rus_18_cap,
        rus_19_cap,
        rus_20_cap,
        rus_21_cap,
        rus_22_cap,
        rus_23_cap,
        rus_24_cap,
        rus_25_cap,
        rus_26_cap,
        rus_27_cap,
        rus_28_cap,
        rus_29_cap,
        rus_30_cap,
        rus_31_cap,
        rus_32_cap,
        rus_33_cap,

        period,
        exclamation_mark,
        question_mark,
        number,
        lower_quote,
        upper_quote,
        minus,
        plus,
        equals,
        slash,
        open_parenthesis,
        close_parenthesis,
        semicolon,
        email,
        hash,
        dollar,
        ampersand,
        backslash,
        open_square_bracket,
        close_square_bracket,
        open_curly_bracket,
        close_curly_bracket,
        less_than,
        greater_than,
        percent,
        tilde,
        underscore,


        //special (no image)
        space,
        nextline,
        tab,
        linebreak, //allows word wrapping

        align_center,
    }
}
